replicaCount: 1

image:
  repository: smartcitiesdata/flair
  tag: development
  pullPolicy: IfNotPresent

localstack:
  enabled: false

kafka:
  #comma delimited list of kafka seed brokers
  brokers: streaming-service-kafka-bootstrap.streaming-prime:9092
  strimziCluster: streaming-service # http://strimzi.io/docs/0.4.0/#_topic_configmap

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 300m
    memory: 3Gi
  requests:
    cpu: 100m
    memory: 3Gi

nodeSelector: {}

tolerations: []

affinity: {}

flair:
  dlq_topic: streaming-dead-letters
  data_topic: streaming-persisted

presto:
  user: "flair"
  url: http://kdp-kubernetes-data-platform-presto.kdp:8080

redis:
  host: redis.external-services
